In [1]:
#importing Libraries

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import numpy as np


#importing Dataset

dataset = ("loan_stat542.csv")
df = pd.read_csv(dataset)

In [2]:
#Data Preprocessing


#Removing Rows Containing Empty Values
df = df.dropna(how='any')

#term   removing string "months"
df.term = df.term.str.replace('months', '').astype(int)

#loan_status   standardizing and droping rows with deafult valaue 
df = df.drop(13887)
df = df.drop(34900)
df = df.drop(64543)

# Normalizing Loan Status
le_loan_status = LabelEncoder()
df['loan_status'] = le_loan_status.fit_transform(df['loan_status'])

# int_rate   converting float into int 
df.int_rate = round(df.int_rate).astype(int)

#installment   convertig float into int
df.installment = round(df.installment).astype(int)

# grade  standardizing
le_grade = LabelEncoder()
df['grade'] = le_grade.fit_transform(df['grade'])

# sub_grade  standardizing
le_sub_grade = LabelEncoder()
df['sub_grade'] = le_sub_grade.fit_transform(df['sub_grade'])

# Normalizing emp_title
le_emp_title = LabelEncoder()
df['emp_title'] = le_emp_title.fit_transform(df['emp_title'])

#emp_length   removing string part
df.emp_length = df.emp_length.str.replace('years', '')
df.emp_length = df.emp_length.str.replace('year', '')
df.emp_length = df.emp_length.str.replace('<', '')
df.emp_length = df.emp_length.str.replace('>', '')
df.emp_length = df.emp_length.str.replace('+', '').astype(int)

#home_ownership  Standardization
le_home_ownership = LabelEncoder()
df['home_ownership'] = le_home_ownership.fit_transform(df['home_ownership'])

#verification_status    Standardization
le_verification_status = LabelEncoder()
df['verification_status'] = le_verification_status.fit_transform(df['verification_status'])

#purpose    Standardization
le_purpose = LabelEncoder()
df['purpose'] = le_purpose.fit_transform(df['purpose'])

#title    Standardization
le_title = LabelEncoder()
df['title'] = le_title.fit_transform(df['title'])

#zip_code     Standardization
df = df.drop('zip_code', axis=1)

#addr_state     Standardization
le_addr_state = LabelEncoder()
df['addr_state'] = le_addr_state.fit_transform(df['addr_state'])

#dti
df.dti = round(df.dti).astype(int)

#earliest_cr_line     Droping this feature
df = df.drop('earliest_cr_line', axis=1)

#revol_util   Converting from float to int
df.revol_util = round(df.revol_util).astype(float)

#initial_list_status
le_initial_list_status = LabelEncoder()
df['initial_list_status'] = le_initial_list_status.fit_transform(df['initial_list_status'])

#application_type
le_application_type = LabelEncoder()
df['application_type'] = le_application_type.fit_transform(df['application_type'])

In [3]:
#Splitting Data
x = df[['loan_amnt', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'purpose', 'title', 'addr_state', 'dti',
       'fico_range_low', 'fico_range_high', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'application_type', 'mort_acc',
       'pub_rec_bankruptcies']]
y=df['loan_status']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.6, random_state=0)

In [4]:
x.columns

Index(['loan_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'purpose', 'title', 'addr_state', 'dti',
       'fico_range_low', 'fico_range_high', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'application_type',
       'mort_acc', 'pub_rec_bankruptcies'],
      dtype='object')

In [5]:
df.head()

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,loan_status
0,38098114,15000,60,12,337,2,10,10763,10,2,...,6,0,138008,29.0,17,1,0,0,0,1
1,36805548,10400,36,7,321,0,2,20098,8,0,...,17,0,6133,32.0,36,1,0,1,0,0
2,37842129,21425,60,16,516,3,15,14435,6,2,...,10,0,16374,76.0,35,1,0,0,0,1
3,37662224,7650,36,14,260,2,12,19617,1,2,...,11,0,16822,92.0,20,0,0,0,0,0
4,37822187,9600,36,14,327,2,12,612,10,2,...,12,0,16388,59.0,44,0,0,0,0,1

In [6]:
#creating classifer
clf = LogisticRegression(random_state = 0 )
clf.fit(x_train, y_train)
y_predict = clf.predict(x_test)

C:\Users\Ejaz\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [7]:
#Accuracy check
from sklearn.metrics import accuracy_score
print('Accuracy Score: ', accuracy_score(y_test, y_predict))

Accuracy Score:  0.8171985002562512